#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 23 11:13:02 PDT 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim GPU_TB_behav -key {Behavioral:sim_1:Functional:GPU_TB} -tclbatch GPU_TB.tcl -view /home/danny/Documents/school/cpe542/real_time_ray_tracing_engine/gpu_pipeline/GPU_TB_behav.wcfg -log simulate.log"
xsim GPU_TB_behav -key {Behavioral:sim_1:Functional:GPU_TB} -tclbatch GPU_TB.tcl -view /home/danny/Documents/school/cpe542/real_time_ray_tracing_engine/gpu_pipeline/GPU_TB_behav.wcfg -log simulate.log

